### ISSUE TITLE
Forest-robu

### ISSUE THREAD

**Issue by AnnikaSN** [zackfisher/robumeta#11]
Hey, 

Thanks a lot for developing this tool! It's super useful and easy explained! I have one minor issue: When I plot an intercept-only model such as in the example with the oswald data using forest.robu, the plot often displays only a subset of studies. Also when I zoom or export it, it doesn't allow to see all studies and the graph looks as if it was cut off at the top and bottom. It is probably something fairly simple and not necessarily related to robumeta itself, but I couldn't find a solution for it. I was hoping you might know what could resolve this issue. 

Thanks a lot & best wishes, 
Annika

**Comment by AnnikaSN** [comment]
I just exported it using a specific width & height and that worked :-)

**Comment by zackfisher** [comment]
Yeah, as of right now this is a known limitation of forest.robu. As you suggested the workaround involves saving the image with the appropriate dimensions. Something like the following,

forest.robu(oswald_intercept, es.lab = "Crit.Cat", study.lab = "Study", "Effect Size" = effect.size, "Weight" = r.weights)       
dev.copy(png, "myForestPlot.png", width=450, height=900, units="px", res=72)
dev.off()

where width and height are adjusted appropriately.  When I originally looked into this it wasn't clear if it was possible to resize the plot automatically but I am going to revisit this soon.

**Comment by AnnikaSN** [comment]
Awesome, thanks!
