### ISSUE TITLE
forest.robu showing no plot

### ISSUE THREAD

**Issue by jurbrauers** [zackfisher/robumeta#15]
Dear team,

Thank you for your work on this intuitive package! Currently, I experience an issue when I try to plot the results of the example provided. When I run the code for the Oswald example no plot is created and when I assign it to an object and run it results in the following: "NULL". I could not find any solution online, am I missing something here?

I installed the grid & clubSandwich packages and tried something that was suggested in another issue:
forest.robu(oswald_intercept, es.lab = "Crit.Cat", study.lab = "Study", "Effect Size" = effect.size, "Weight" = r.weights)
dev.copy(png, "myForestPlot.png", width=450, height=900, units="px", res=72)
dev.off()

Running this results in the following: 
quartz_off_screen 
                3 
quartz_off_screen 
                2 

I hope that you have any suggestions on how to fix this.

Kind regards,
Jur

**Comment by jurbrauers** [comment]
It seems that changing some of my settings for markdown creates a workaround (found the solution [here](https://stackoverflow.com/questions/38068774/rstudio-suddenly-stopped-showing-plots-in-in-plot-pane))

Go to Tools->Global Options->Rmarkdown
In "Show output preview in" select "Viewer Pane"
Uncheck the box "Show output inline for all R Markdown documents"

Sorry for the inconvenience.

**Comment by zackfisher** [comment]
Jur, thanks for following up and for pointing to the solution. Closing this issue for now.
