### ISSUE TITLE
Issues with forest.robu 

### ISSUE THREAD

**Issue by rwonggg** [zackfisher/robumeta#16]
Hi, I'm trying to use robumeta for my dissertation. I tried to create a forest plot with forest.robu but I keep getting this error "subscript out of bounds". What's even more confusing is that I've run this same code for two other sets of data and they both worked. I can't figure out what I am doing wrong here. I've checked my data and everything looks okay; no missing data, not issues with coding. In fact, everything that's coded in this dataset is similar to that of the other two dataset that ran with forest.robu. 

Please advise. 

forest.robu(z, es.lab = "DV", study.lab="Study", "Weights"=r.weights, "Hedges' g" = effect.size)

Error in col$values[[i]] : subscript out of bounds

**Comment by zackfisher** [comment]
I've never come across this specific error before in regard to forest.robu() before so you'll need to provide a small reproducible example. Also, what versions of R and robumeta you are using.

**Comment by rwonggg** [comment]
I'm using R version 4.0.4 and robumeta 2.0. 
Yes, I've run this code 3 times now and 2 out of the 3 times worked fine. The third time just wouldn't work at all and I keep getting this error. 


I've attached the dataset I'm working with. I just can't figure out if this is an issue with the data I'm uploading... however, the previous code works fine: 

res<-robu(formula = yi~1, var.eff.size = vi, studynum = Same.Study, rho = 0.8, small=TRUE, modelweights = "CORR", data=x)
print(res)

I'm not sure if this helps.

**Comment by zackfisher** [comment]
Your 'Study' and 'Same.Study' variables don't match. Namely, you have two studies with the label "Okebukola, P. A. (1992)" being treated as separate studies.

**Comment by rwonggg** [comment]
Ah. Thank you so much for catching this! After fixing it, my code works. Sorry for troubling you. I will go ahead and delete the above comment with my data.

**Comment by yezikang0515** [comment]
hi, i also met problems with forest plot, my problem is that i can not plot. i tried the data from _help_ provided by R in _robumeta_packages, the code rans well but the plot didn't came out. i don't know if it is i do not install any packages. now i installed metafor, robumeta and grid.
many thanks
