### ISSUE TITLE
forest.robu yields "subscript out of bounds" & questions about variance explained

### ISSUE THREAD

**Issue by alecristia** [zackfisher/robumeta#17]
Thank you for a fantastic package.

We have a dataset with the correlations between young children's response times (RT) & socioeconomic status (SES), on the one hand; and  accuracies & socioeconomic status on the other; collected with 3 tests (LwL, PPVT, TVT). Some studies report both RT & accuracy for the same group of children; most report only one.[^1] RTs are available for LwL & TVT (only one study has RTs for PPVT). 

Here's our data: [mwe.csv](https://github.com/zackfisher/robumeta/files/7344506/mwe.csv)

We:

1. used `escalc` from `metafor` to get yi=zcor & vi
2. checked that there are no missing values, no outliers, vi is positive
3. read the vignette & chose HIER (while children's RT and accuracy are probably correlated, no study reported this; AND more importantly, we are looking here at the correlation RT-SES & accuracy-SES and we don't know whether these two *correlations* are correlated, so it seems more logical to use the HIER model to indicate the mutual dependencies 

The following models fit, but I cannot get the forest plot out:

```r
robu_fit_base <- robu(yi ~ 1, data = mydat,
                 modelweights = "HIER", studynum = infant_group,
                 var.eff.size = vi)

forest.robu(robu_fit_base)

robu_fit_age <- robu(yi ~ age.min, data = all,
                 modelweights = "HIER", studynum = infant_group,
                 var.eff.size = vi)
robu_fit_age_exp <- robu(yi ~ age.min*expected, data = all,
                 modelweights = "HIER", studynum = infant_group,
                 var.eff.size = vi)

robu_fit_age_test <- robu(yi ~ age.min*comp_measure_cat, data = all,
                 modelweights = "HIER", studynum = infant_group,
                 var.eff.size = vi)
```

"omega.sq is the between-studies-within-cluster variance component for the hierarchical effects meta-regression model." It is zero in all of these models. It's not impossible that our measures are super noisy to the point that there is no systematic variance attributed to the repeated measures. Is that the right interpretation?

"tau.sq is the between-cluster variance component in the hierarchical effects model". This is very small in all of these models. So studies do not vary systematically very much.  Is that the right interpretation?

`metafor` also provides a test for heterogeneity and I^2 (total heterogeneity / total variability), which gives us an idea of the extent to which we still have variance to explain. Given that omega.sq is so small, would it be reasonable to fit the models using `metafor` so as to be able to report to our readers/reviewers these results on heterogeneity?

[^1]: We flipped the direction of the correlation for RTs (faster is better), so that higher correlation indicates stronger relationship for both RTs and accuracy. We use the column "expected" to separate RTs from accuracies -- expected== positive --> accuracy; expected ==negative --> RT.

**Comment by zackfisher** [comment]
Hi Alex,

Thanks for the detailed email. In regard to your robumeta issue, you need to supply study and effect size labels to the forest.robu function. In my next update I'll add a more informative error message when those arguments are omitted.

In regards to your questions about the HE working model you might want to check out this recent paper by @jepusto and @marianolake. They provide some additional working models (beyond HE and CE) and you may find a more realistic match for your analysis.

https://osf.io/preprints/metaarxiv/vyfcj/

Hope that helps!

Zack
