### ISSUE TITLE
Forest.robu

### ISSUE THREAD

**Issue by florinaerbeli** [zackfisher/robumeta#18]

**Comment by zackfisher** [comment]
Let me take a look. [Edit]

**Comment by florinaerbeli** [comment]
As requested, I emailed you the .csv file along with the R script I am using. Thank you!

**Comment by zackfisher** [comment]
Could you also provide me with the code for fitting modelURE_r_c. Thanks.

**Comment by florinaerbeli** [comment]
> Could you also provide me with the code for fitting modelURE_r_c. Thanks.

Sure thing. I emailed the R script and the data to this email address zff100@psu.edu Pllease let me know if I should email it somewhere else.

**Comment by florinaerbeli** [comment]
`Multi.MA = read.csv("PACodebook_RR1 RRQ_021222_byFE.csv",
                  stringsAsFactors = F, header = T)
summary(Multi.MA)

##################################################################################################

# Unconditional RE model in robumeta with correlational weights
modelURE_r_c <- robu(d.unbiased ~ 1, 
                  studynum = Study.Type.R,
                  var.eff.size = d.unbiased.var,
                  data = Multi.MA,
                  modelweights = "CORR",
                  rho = .80)
modelURE_r_c`

**Comment by florinaerbeli** [comment]
Multi.MA = read.csv("PACodebook_RR1 RRQ_021222_byFE.csv",
stringsAsFactors = F, header = T)
summary(Multi.MA)

#################Unconditional RE model in robumeta with correlational weights

modelURE_r_c <- robu(d.unbiased ~ 1,
studynum = Study.Type.R,
var.eff.size = d.unbiased.var,
data = Multi.MA,
modelweights = "CORR",
rho = .80)
modelURE_r_c

**Comment by zackfisher** [comment]
Your data file has an extra row. Remove the final row (almost all NAs, including the study labels and effect sizes) and your code works. Hope that helps.

**Comment by florinaerbeli** [comment]
> Your data file has an extra row. Remove the final row (almost all NAs, including the study labels and effect sizes) and your code works. Hope that helps.

Goh, I am quite embarrassed about this rookie mistake. One question - is this option available to include CIs in the forestplot output? "CI Lower"=CI.L, "CI Upper"=CI.U
