### ISSUE TITLE
error with predict function

### ISSUE THREAD

**Issue by arkurup** [zackfisher/robumeta#20]
Hi there, I'm hoping this is the right place to inquire about this. I was trying to use the predict function to get estimates at different dummy-coded levels of my moderator and I just couldn't get it to work. I tried to run the example code in the help page and got the same error, which is:

Error in stats::qt(1 - (1 - level)/2, df) : 
  Non-numeric argument to mathematical function

I can't figure out what's wrong; I dummy-coded my variable appropriately and have specified the "pred.vector" in the way it's described on the help page (intercept, dummy codes) but I simply can't get it to work. I was wondering if even the example code doesn't run/produces the same error, could it be something in the actual code? 

I'm happy to share more of my own code if needed. It would be so awesome if I could get some help figuring out what is happening. Thanks in advance for any help!!

**Comment by andreizhirnov** [comment]
I have encountered the same issue. It looks like the updated version of  clubSandwich::Wald_test (at least its current version) uses "FStat" and "df_denom" instead of "F" and "df".  predict.robu() uses the old names internally.

**Comment by zackfisher** [comment]
OK, I thought this was updated in clubSandwich to not break continuity with older versions of the package. I'll push an update using the new syntax. Would you be able to provide a minimal example that reproduces the error?

**Comment by andreizhirnov** [comment]
For instance, this:
library(robumeta)
data(hierdat)
test <-  robu(formula = effectsize ~ binge , data = hierdat, studynum = studyid, 
                   var.eff.size = var, modelweights = "HIER", small = TRUE)
predict(object = test, pred.vector = c(1,0.5),level = 0.95)

**Comment by andreizhirnov** [comment]
it uses clubSandwich_0.5.7 and robumeta_2.0

**Comment by einsley1993** [comment]
Hi @zackfisher ,

I'm running into the same error as the OP. Would you have any updates on the issue? I am running the example provided in this package's documentation:

library(clubSandwich)
robu_mod <- robu(LOR1 ~ study_design + duration + service_hrs, 
                 data = dropoutPrevention, 
                 studynum = studyID, 
                 var.eff.size = varLOR, 
                 modelweights = "HIER",
                 small = TRUE)

predict(object = robu_mod, pred.vector = c(1,0,0,38,5),level = 0.95)

Thank you so much!

Best,
Yi

**Comment by zackfisher** [comment]
This works for the version of robumeta currently on GitHub. I also just pushed an update to Cran so the fix should be available shortly.

**Comment by einsley1993** [comment]
thank you so much!
